from .analytics_robot import AnalyticsRobot
from .cutter_robot import CutterRobot
from .description_robot import DescriptionRobot
from .download_robot import DownloadRobot
from .tags_robot import TagsRobot
from .thumbnail_robot import ThumbnailRobot
from .title_robot import TittleRobot
from .twitter_robot import TwitterRobot
from .upload_robot import UploadRobot
from .speech_recognizer_robot import SpeechRecognizerRobot
from .audio_extractor_robot import AudioExtractorRobot
from .user_input_robot import UserInputRobot